version: "3.8"

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - private
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgres:
    image: "postgres"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: messaging
    ports:
      - "5432:5432"
    networks:
      - private
    depends_on:
      - rabbitmq
    volumes:
      - postgres_data:/var/lib/postgresql/data

  graphql:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - private
    depends_on:
      - rabbitmq
      - postgres

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      - private
    depends_on:
      - graphql

networks:
  private:

volumes:
  rabbitmq_data:
  postgres_data:
